# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 030a41a65aa9ddebbb0995b35eb4c48d70f76776e5a2984b26712f2e523e77733bf049a1b916ca8352d8ff453f927a5ba4c0a0b0d9125ca62848973fdd9d098a

test:
  secret_key_base: f116549d26228bdf35fa24701f4c2ffd6f987f97b3444fe908b002256a73bc053bdecd6a0b092ed07338d90d23d3bf97550bb48b0eb74903ed11d129906def08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
